### ISSUE TITLE
API cannot connect to Dataverse from Harvard Odyssey compute nodes

### ISSUE THREAD

**Issue by MKLau** [IQSS/dataverse-client-python#45]
We're (@cscn) working on a project that accesses Dataverse from Harvard's Odyssey Cluster. We've run into an issue with establishing a connection via the Python API. 

We've contacted Research Computing and they've narrowed the issue down to the following (from RC):

"Thank you for your message. I ran a few tests and it seems the issue is that "dataverse" cannot be accessed from our compute nodes. For instance, I get  

curl -u $API_TOKEN: https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/service-document
curl: (7) couldn't connect to host

On the other hand, if I use the "demo.dataverse.org" host as explained in their examples, everything works fine, i.e.,

curl -u $API_TOKEN: https://demo.dataverse.org/dvn/api/data-deposit/v1.1/swordv2/service-document

This makes me think they should be able to adjust their settings and make them similar to the ones of demo.dataverse.org."

Would the suggested change be possible? Or, do you suggest an alternative?

Thanks!

Matt

**Comment by pdurbin** [comment]
@MKLau that's very strange. At the moment we are moving https://dataverse.harvard.edu from physical servers hosted at Harvard to AWS so can you please try again after the move? You'll know the move is complete when the maintenance page has been removed.

**Comment by MKLau** [comment]
Hi Phil, thanks for letting me know. What's the ETA on the switch to AWS?

**Comment by pdurbin** [comment]
@MKLau it's done! If you go to the homepage, you should see an orange note that you can expand to read the following:

"We've changed hosting! Contact us if you see any issues.

Harvard Dataverse has recently changed hosting from an on-campus Harvard data center to a cloud provider (AWS). This infrastructure upgrade is intended to provide greater storage capabilities, more stability, and decreased cost. We are currently keeping a close eye to ensure that the transition was fully successful.

If you notice any service deficits such as downtime, slower speeds, 404s, or other errors, please email us at support@dataverse.harvard.edu"

Actually, this feels like an issue specific to Harvard's installation of Dataverese rather than the 30 other installations around the world. If you're still having trouble, can you please email support@dataverse.harvard.edu so that we can track this problem as a support ticket?

**Comment by MKLau** [comment]
Hi Phil, thanks! Per your request, I'll contact support with further issues.

**Comment by MKLau** [comment]
FYI - just ran the previous test on Odyssey and we no longer get this error. Closing the issue. 

Thanks Phil!

**Comment by pdurbin** [comment]
@MKLau great! Thanks for letting us know.
